$primary = rgb(faacf9)
$surface = rgb(161215)
$secondary = rgb(d8bfd4)
$error = rgb(ffb4ab)
$tertiary = rgb(f6b8ab)
$surface_lowest = rgb(110d10)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
